name: Paramount
main: ml.para.plugin.Main
version: 1.0
author: AndrewIsDank
commands:
  heal:
    description: Heals the target player
  feed:
    description: Feeds the target player
  s:
    description: Changes gamemode
  c:
    description: Changes gamemode
  a:
    description: Changes gamemode
  spec:
    description: Changes gamemode
  rip:
    description: Rekt M8